---
title: "Ejemplos de Tidyverse"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Ejemplos de Tidyverse

## Preparativos carga de paquetes 

```{r carga librerias, message = FALSE}
# dplyr
library(dplyr)

#ggplot
library(ggplot2)
```

## Carga de datos

```{r carga-datos}

# Carga de datos desde un archivo CSV
rios <-
  read.csv(file = 'https://raw.githubusercontent.com/tpb728O-programaciongeoespacialr/2021ii/main/datos/hidrologia/fdc/fdc.csv')

# Carga de datos desde un archivo CSV
covid <- 
  read.csv(
    file='https://raw.githubusercontent.com/tpb728O-programaciongeoespacialr/2021ii/main/datos/minsalud/covid/ultimafecha_CSV_GENERAL.csv', 
    sep = ","
  )

```

## dplyr

### mutate()

```{r}
# EStructura del data frame 
str(rios)

```
```{r funciones-enlazadas}
# Despliegue de los primeros registros
 rios %>% slice_head(n = 5) %>%  slice_tail(n = 2)
```
```{r funciones anidadas}
# Funciones anidadas

```

```{r ejemplo mutate}
# Cambio de nombre de las columnas mediante rename()
rios <-
  rios %>%
  rename(fecha = Tiempo,
         pandora = Pandora.mm..637km2.,
         banano = Banano.mm..90km2.)

# Conversión de una columna a tipo Date y creación de una nueva columna
rios <-
  rios %>%
  mutate(fecha = as.Date(fecha, format = "%m/%d/%Y"),
         promedio = (pandora + banano) / 2)

slice_head(rios, n = 10)


```
### Select()

```{r seleccionado}
# Selección, renombramiento y conversión de columnas
covid_columnas_seleccionadas <-
  covid %>%
  select(FECHA, muj_posi, hom_posi) %>%
  rename(
    fecha = FECHA,
    positivos_mujeres = muj_posi,
    positivos_hombres = hom_posi
  ) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y"))

slice_head(covid_columnas_seleccionadas, n = 10)
```
### Filter ()
```{r filtrado}
# Selección, renombramiento, conversión de columnas y filtrado
covid_filtrado <-
  covid %>%
  select(FECHA, nue_posi) %>%
  rename(fecha = FECHA, positivos_nuevos = nue_posi) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y")) %>%
  filter(positivos_nuevos >= 3000)

slice_head(covid_filtrado, n = 20)

# Despliegue del data frame con los resultados
covid_filtrado
```

### Arange()
```{r ordenar}
# Selección, renombramiento, filtrado y conversión de columnas
covid_filtrado_ordenado_x_positivos_nuevos <-
  covid %>%
  select(FECHA, nue_posi) %>%
  rename(fecha = FECHA, positivos_nuevos = nue_posi) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y")) %>%
  filter(positivos_nuevos >= 2500) %>%
  arrange(desc(positivos_nuevos))

slice_head(covid_filtrado_ordenado_x_positivos_nuevos, n = 20)
# Despliegue del data frame con los resultados
covid_filtrado_ordenado_x_positivos_nuevos



```
### Summarise()

```{r ejemplo sumarize-01}
# Selección, renombramiento, filtrado y conversión de columnas por mes y anio
covid_positivos_nuevos_sumarizado_x_aniomes <-
  covid %>%
  select(FECHA, nue_posi) %>%
  rename(fecha = FECHA, positivos_nuevos = nue_posi) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y")) %>%
  group_by(anio = format(fecha,"%Y"), mes = format(fecha,"%m")) %>%
  summarise(suma_positivos = sum(positivos_nuevos))

# Despliegue del data frame con los resultados
covid_positivos_nuevos_sumarizado_x_aniomes
```
```{r ejemplo sumarize-02}
# Selección, renombramiento, filtrado y conversión de columnas solo por mes
covid_positivos_nuevos_sumarizado_x_mes <-
  covid %>%
  select(FECHA, nue_posi) %>%
  rename(fecha = FECHA, positivos_nuevos = nue_posi) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y")) %>%
  group_by(mes = format(fecha,"%m")) %>%
  summarise(suma_positivos = sum(positivos_nuevos))

# Despliegue del data frame con los resultados
covid_positivos_nuevos_sumarizado_x_mes
```
```{r ejemplo sumarize-03}
# Selección, renombramiento, filtrado y conversión de columnas solo por mes en promedio
covid_positivos_nuevos_sumarizado_x_prommes <-
  covid %>%
  select(FECHA, nue_posi) %>%
  rename(fecha = FECHA, positivos_nuevos = nue_posi) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y")) %>%
  group_by(mes = format(fecha,"%m")) %>%
  summarise(suma_positivos = mean(positivos_nuevos))

# Despliegue del data frame con los resultados
covid_positivos_nuevos_sumarizado_x_prommes
```